name: Enforced CI

on:
  workflow_call:

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ruff (blocking)
        run: ruff check .

      - name: Run pytest
        run: |
          chmod +x test.sh
          ./test.sh --full
